services:
  - type: web
    name: pollspace-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://poll-space-a-realtime-polling-system-hdo8ecdxw.vercel.app
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "8001"